Do not open more than one migration or on-disk representation file at a time (#173)
* Delay opening files until first read

This doesn't come even close to fixing the issue, but felt like a good
place to start.

* Close file handles when file Streams are fully read

This still doesn't solve the issue, but will likely play an important
role, as code elsewhere won't have to worry about explicitly closing
files when they're done with them.

This shouldn't be a problem because we can't rewind file streams and
because `hClose` can be called more than once on the same handle.

* Finally make at most one migration file be open at a time

This is not a pretty implementation.
Env vars to be templated are stored in each `SqlMigration` object (both
their names and values), and one of the functions that return migrations
and streams from disk higher up in the internal layers of the codebase
now reads that, closes the stream it had before and opens a new one.

That new FileStream is returned by calling the parser again and overriding
specific parts of the returned record, assuming the file won't change
in between the two moments it is opened (I don't think we can escape
this assumption regardless of implementation if we want to parse+report
errors in migrations before we start applying them).

* Slightly better function name and docs

* Add strace test

* Fix files with `no-parse` being opened more than once.

* Add sanity check and no longer require dev-shell postgres server to test

* Parse musl's `open` too, strace-wrap exclusively test executable

And cleanup argv handling in the Runfile

* There's no strace for darwin

* Use a less common name for the strace log file

* Run tests in CI

* Also test on-disk representations. Make sure the parsers never fail.

* Tidy up imports in new test file

* Fix Runfile targets

* Don't run system resources tests in installer variant

Because they will obviously fail without strace-wrapping,
and it's not worth implementing it for them.

diff --git a/Runfile b/Runfile
--- a/Runfile
+++ b/Runfile
@@ -16,12 +16,15 @@ ci-tests:
     # not the IOHK one. We assume differences in the codebase regarding different
     # postgres versions aren't enough to make it worth testing every version here too.
     echo "Running all tests on Postgres 16 with nixpkgs's cabal2nix derivation of codd"
-    nix-build ./nix/install-codd-nixpkgs.nix -A coddWithCheck
+    nix-build ./nix/install-codd-nixpkgs.nix --no-link -A coddWithCheck
 
     run test-with-db --nix --pg 15
     run test-with-db --nix --pg 14
     run test-with-db --nix --pg 13
     run test-with-db --nix --pg 12
+
+    echo "Running system-resources test"
+    run test-system-resources --nix
 
 ##
 # Formats all Haskell files with brittany.
@@ -53,27 +56,22 @@ format-hs:
 # all tests that don't require a database.
 # OPTION NIX --nix Use a Nix-built test executable instead of compiling with cabal in the user's shell.
 # OPTION NONIXBUILD --nonixbuild Assume the test executable has already been build with Nix. Option used mostly internally.
+# OPTION STRACE --strace Wrap test execution with strace. Useful for a very specific test or for debugging.
 test-no-db:
     set -eo pipefail
+    TARGS=( "$@" ) && [ -z "$1" ] && TARGS=(--skip /DbDependentSpecs/ --skip /SystemResourcesSpecs/)
+    STRACECMD=() && [ -n "$STRACE" ] && STRACECMD=(strace -f -e openat,open,close -o /tmp/strace-codd-system-resources-test.log)
     if [ -n "$NIX" ]; then
-
         # This Run command is used insire pure Nix shells where `nix` is not available. That's why
         # this option is useful.
         if [ -z "$NONIXBUILD" ]; then
             nix build ".#x86_64-unknown-linux-musl:codd:test:codd-test" -o local/codd-test
         fi
 
-        if [ -n "$1" ]; then
-            ./local/codd-test/bin/codd-test "$@"
-        else
-            ./local/codd-test/bin/codd-test --skip "/DbDependentSpecs/"
-        fi
+        "${STRACECMD[@]}" ./local/codd-test/bin/codd-test "${TARGS[@]}"
     else
-        if [ -n "$1" ]; then
-            cabal run -O0 codd-test -- "$@"
-        else
-            cabal run -O0 codd-test -- --skip "/DbDependentSpecs/"
-        fi
+        cabal build -O0 codd-test
+        "${STRACECMD[@]}" `cabal list-bin -O0 codd-test` "${TARGS[@]}"
     fi
 
 ## 
@@ -85,6 +83,9 @@ test-with-db:
     set -eo pipefail
     [ -z "$PG" ] && PG=(16)
     [ "${PG[0]}" = "all" ] && PG=(12 13 14 15 16)
+    NIXA=() && [ -n "$NIX" ] && NIXA=(--nix)
+    NIXDEVARGS=() && [ -n "$NIX" ] && NIXDEVARGS=(-i)
+    TARGS=(--match /DbDependentSpecs/) && [ -n "$1" ] && TARGS=("$@")
 
     # Build the test executable only once with Nix
     if [ -n "$NIX" ]; then
@@ -93,24 +94,40 @@ test-with-db:
     
     for pg in "${PG[@]}"; do
         echo "Running tests on Postgres $pg"
-        if [ -n "$NIX" ]; then
-            nix develop ".#testShells.x86_64-linux.pg${pg}" -i -c run test-with-db-internal --nix -- "$@"
-        else
-            nix develop ".#testShells.x86_64-linux.pg${pg}" -c run test-with-db-internal -- "$@"
-        fi
+        nix develop ".#testShells.x86_64-linux.pg${pg}" "${NIXDEVARGS[@]}" -c run test-with-db-internal "${NIXA[@]}" -- "${TARGS[@]}"
     done
 
 ##
 # Do not use this. Use the `test-with-db` command instead.
 # OPTION NIX --nix Use a Nix-built test executable instead of compiling with cabal in the user's shell.
+# OPTION STRACE --strace Wrap test execution with strace. Useful for a very specific test or for debugging.
 test-with-db-internal:
     set -eo pipefail
     trap "echo Stopping postgres && pg_ctl stop" EXIT
-    NIXA=()
-    [ -n "$NIX" ] && NIXA=("--nix")
+    NIXA=() && [ -n "$NIX" ] && NIXA=(--nix)
+    STRACEA=() && [ -n "$STRACE" ] && STRACEA=(--strace)
+    TARGS=(--skip /DbDependentSpecs/ --skip /SystemResourcesSpecs/) && [ -n "$1" ] && TARGS=("$@")
 
-    if [ -z "$1" ]; then
-        run test-no-db "${NIXA[@]}" --nonixbuild -- --match "/DbDependentSpecs/"
+    run test-no-db "${NIXA[@]}" "${STRACEA[@]}" --nonixbuild -- "${TARGS[@]}"
+
+##
+# Test that codd does not open more than one migration file or on-disk representation file simultaneously, so that it won't fail in shells or OS's with tight open file limits.
+# OPTION NIX --nix Use a Nix-built test executable instead of compiling with cabal in the user's shell.
+test-system-resources:
+    set -eo pipefail
+
+    if ! command -v strace &> /dev/null
+    then
+        echo strace could not be found. You need strace installed for this test.
+        exit 1
+    fi
+
+    rm -f /tmp/strace-codd-system-resources-test.log
+    trap "rm -f /tmp/strace-codd-system-resources-test.log" ERR EXIT
+
+    if [ -n "$NIX" ]; then
+        nix build ".#x86_64-unknown-linux-musl:codd:test:codd-test" -o local/codd-test
+        nix develop ".#testShells.x86_64-linux.pg16" -i -c run test-with-db-internal --strace --nix -- --match "/SystemResourcesSpecs/"
     else
-        run test-no-db "${NIXA[@]}" --nonixbuild -- "$@"
+        nix develop ".#testShells.x86_64-linux.pg16" -c run test-with-db-internal --strace -- --match "/SystemResourcesSpecs/"
     fi
